name: nuget-publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet Org package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1 

      - name: Build solution and generate NuGet package
        run: |  
          cd Valentemesmo.Railway
          dotnet pack -c Release -o out

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
        with:                    
          nuget-api-key: ${{secrets.NUGET_KEY}} 

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Valentemesmo.Railway/out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}} --skip-duplicate
